#!/usr/bin/env node
var util = require('./util'),
    FILES = [
      ['presto', 'lib/presto'],
      ['presto/util', 'lib/presto/util'],
      ['presto/policy', 'lib/presto/policy'],
      ['presto/s3-file', 'lib/presto/s3-file'],
      ['presto/upload', 'lib/presto/upload'],
      ['id3', 'node_modules/id3js/dist/id3']
    ];

var src = util.compileManyFiles(FILES);
util.write('dist/presto.js', src);
console.log('Written to dist/presto.js');
