#!/usr/bin/env node
var src, util = require('./util'),
    FILES = [
      ['presto', 'lib/presto'],
      ['presto/id3', 'lib/presto/id3'],
      ['presto/api', 'lib/presto/api'],
      ['presto/util', 'lib/presto/util'],
      ['presto/upload', 'lib/presto/upload'],
      ['presto/cover', 'lib/presto/cover']
    ];

src = util.compileManyFiles(FILES);
util.write('dist/presto.js', src);
console.log('Written to dist/presto.js');

