#!/usr/bin/env node
var Compiler = require("es6-module-transpiler").Compiler,
    fs = require('fs');

var copyFile = function(from, to) {
  console.log('Copying', from, 'to', to);
  var src = fs.readFileSync(from);
  fs.writeFileSync(to, src);
};

copyFile('node_modules/mocha/mocha.js', 'spec/vendor/mocha.js');
copyFile('node_modules/mocha/mocha.css', 'spec/vendor/mocha.css');
copyFile('node_modules/expect.js/index.js', 'spec/vendor/expect.js');
